reportmaker/reporter/urls.py
from django.conf.urls import url

from . import views

app_name = 'reporter'

urlpatterns = [
	url(r'^$', views.index, name='index'),

	url(r'^login/$', views.user_login, name='login'),
	url(r'^logout/$', views.user_logout, name='logout'),

	url(r'^reports/$', views.ReportListView.as_view(), name='reports'),
	url(r'^reports/create/$', views.create, name='create'),
	url(r'^reports/(?P<report_id>[0-9]+)/$', views.ProcessListView.as_view(), name='report'),
	url(r'^reports/(?P<report_id>[0-9]+)/edit/$', views.edit, name='report_edit'),
	url(r'^reports/(?P<report_id>[0-9]+)/remove/$', views.remove, name='report_remove'),
	url(r'^reports/(?P<report_id>[0-9]+)/download/word$', views.download_word, name='download_word'),
	url(r'^reports/(?P<report_id>[0-9]+)/download/excel$', views.download_excel, name='download_excel'),
]

reportmaker/reportmaker/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('reporter.urls')),
]

reportmaker/reporter/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models


class Report(models.Model):
	title_text = models.CharField(max_length=200)
	content_text = models.CharField(max_length=1000)
	pub_date = models.DateTimeField()
	interval_update = models.IntegerField(default=30)

	def __str__(self):
		return self.title_text


class Process(models.Model):
	report = models.ForeignKey(Report, on_delete=models.CASCADE)
	name_text = models.CharField(max_length=50)
	state_text = models.CharField(max_length=20)
	ram_in_kb_int = models.PositiveIntegerField()
	date = models.DateTimeField()

	def __str__(self):
		return self.name_text

reportmaker/reporter/forms.py
from django import forms


class ReportForm(forms.Form):
	title_text = forms.CharField(label='title', max_length=200)
	content_text = forms.CharField(label='content', max_length=1000)

reportmaker/reporter/views.py
import datetime
import mimetypes
import os

from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.views import generic

from .models import Report, Process
from .forms import ReportForm


class ReportListView(LoginRequiredMixin, generic.ListView):
	login_url = '/login'
	template_name = 'reporter/report_list.html'
	filters = {
		'id': '',
		'title': '',
		'title_match': '',
		'content': '',
		'content_match': '',
		'date': ''
	}

	def get_queryset(self):
		reports = Report.objects.all()
		if self.request.method == 'GET':
			self.filters['id'] = self.request.GET.get('id')
			self.filters['title'] = self.request.GET.get('title')
			self.filters['title_match'] = self.request.GET.get('title_match')
			self.filters['content'] = self.request.GET.get('content')
			self.filters['content_match'] = self.request.GET.get('content_match')
			self.filters['date'] = self.request.GET.get('date')
			self.filters['date_match'] = self.request.GET.get('date_match')

			if self.filters['id']:
				reports = reports.filter(id=self.filters['id'])

			if self.filters['title']:
				if self.filters['title_match'] == 'exact':
					reports = reports.filter(title_text__iexact=self.filters['title'])
				elif self.filters['title_match'] == 'starts':
					reports = reports.filter(title_text__istartswith=self.filters['title'])
				elif self.filters['title_match'] == 'contains':
					reports = reports.filter(title_text__icontains=self.filters['title'])
				elif self.filters['title_match'] == 'ends':
					reports = reports.filter(title_text__iendswith=self.filters['title'])

			if self.filters['content']:
				if self.filters['content_match'] == 'exact':
					reports = reports.filter(content_text__iexact=self.filters['content'])
				elif self.filters['content_match'] == 'starts':
					reports = reports.filter(content_text__istartswith=self.filters['content'])
				elif self.filters['content_match'] == 'contains':
					reports = reports.filter(content_text__icontains=self.filters['content'])
				elif self.filters['content_match'] == 'ends':
					reports = reports.filter(content_text__iendswith=self.filters['content'])

			if self.filters['date']:
				date = [int(item) for item in self.filters['date'].split("-")]
				if self.filters['date_match'] == 'equal':
					reports = reports.filter(pub_date__date=datetime.date(date[0], date[1], date[2]))
				elif self.filters['date_match'] == 'greater':
					reports = reports.filter(pub_date__date__gt=datetime.date(date[0], date[1], date[2]))
				elif self.filters['date_match'] == 'e_greater':
					reports = reports.filter(pub_date__date__gte=datetime.date(date[0], date[1], date[2]))
				elif self.filters['date_match'] == 'less':
					reports = reports.filter(pub_date__date__lt=datetime.date(date[0], date[1], date[2]))
				elif self.filters['date_match'] == 'e_less':
					reports = reports.filter(pub_date__date__lte=datetime.date(date[0], date[1], date[2]))

		return reports

	def get_context_data(self, **kwargs):
		context = super(ReportListView, self).get_context_data(**kwargs)
		context['filters'] = self.filters
		return context


class ProcessListView(LoginRequiredMixin, generic.ListView):
	login_url = '/login'
	template_name = 'reporter/report.html'

	filters = {
		'id': '',
		'name': '',
		'name_match': '',
		'state': '',
		'state_match': '',
		'ram': '',
		'date': ''
	}

	def get_queryset(self):
		processes = Process.objects.all()
		processes = processes.filter(report=self.kwargs.get('report_id'))

		if self.request.method == 'GET':
			self.filters['id'] = self.request.GET.get('id')
			self.filters['name'] = self.request.GET.get('name')
			self.filters['name_match'] = self.request.GET.get('name_match')
			self.filters['state'] = self.request.GET.get('state')
			self.filters['state_match'] = self.request.GET.get('state_match')
			self.filters['ram'] = self.request.GET.get('ram')
			self.filters['ram_match'] = self.request.GET.get('ram_match')
			self.filters['date'] = self.request.GET.get('date')
			self.filters['date_match'] = self.request.GET.get('date_match')

			if self.filters['id']:
				processes = processes.filter(id=self.filters['id'])

			if self.filters['name']:
				if self.filters['name_match'] == 'exact':
					processes = processes.filter(name_text__iexact=self.filters['name'])
				elif self.filters['name_match'] == 'starts':
					processes = processes.filter(name_text__istartswith=self.filters['name'])
				elif self.filters['name_match'] == 'contains':
					processes = processes.filter(name_text__icontains=self.filters['name'])
				elif self.filters['name_match'] == 'ends':
					processes = processes.filter(name_text__iendswith=self.filters['name'])

			if self.filters['state']:
				if self.filters['state_match'] == 'exact':
					processes = processes.filter(state_text__iexact=self.filters['state'])
				elif self.filters['state_match'] == 'starts':
					processes = processes.filter(state_text__istartswith=self.filters['state'])
				elif self.filters['state_match'] == 'contains':
					processes = processes.filter(state_text__icontains=self.filters['state'])
				elif self.filters['state_match'] == 'ends':
					processes = processes.filter(state_text__iendswith=self.filters['state'])

			if self.filters['ram']:
				if self.filters['ram_match'] == 'equal':
					processes = processes.filter(ram_in_kb_int=int(self.filters['ram']))
				elif self.filters['ram_match'] == 'greater':
					processes = processes.filter(ram_in_kb_int__gt=int(self.filters['ram']))
				elif self.filters['ram_match'] == 'e_greater':
					processes = processes.filter(ram_in_kb_int__gte=int(self.filters['ram']))
				elif self.filters['ram_match'] == 'less':
					processes = processes.filter(ram_in_kb_int__lt=int(self.filters['ram']))
				elif self.filters['ram_match'] == 'e_less':
					processes = processes.filter(ram_in_kb_int__lte=int(self.filters['ram']))

			if self.filters['date']:
				date = [int(item) for item in self.filters['date'].split("-")]
				if self.filters['date_match'] == 'equal':
					processes = processes.filter(date__date=datetime.date(date[0], date[1], date[2]))
				elif self.filters['date_match'] == 'greater':
					processes = processes.filter(date__date__gt=datetime.date(date[0], date[1], date[2]))
				elif self.filters['date_match'] == 'e_greater':
					processes = processes.filter(date__date__gte=datetime.date(date[0], date[1], date[2]))
				elif self.filters['date_match'] == 'less':
					processes = processes.filter(date__date__lt=datetime.date(date[0], date[1], date[2]))
				elif self.filters['date_match'] == 'e_less':
					processes = processes.filter(date__date__lte=datetime.date(date[0], date[1], date[2]))

		return processes

	def get_context_data(self, **kwargs):
		context = super(ProcessListView, self).get_context_data(**kwargs)
		context['filters'] = self.filters
		context['report'] = get_object_or_404(Report, id=self.kwargs.get('report_id'))
		return context


def index(request):
	return render(request, 'reporter/index.html')


@login_required()
def report(request, report_id):
	report = get_object_or_404(Report, id=report_id)
	return render(request, 'reporter/report.html', {'report': report})


@login_required()
def remove(request, report_id):
	if request.method == 'POST':
		Report.objects.get(id=report_id).delete()
		return HttpResponseRedirect('/reports/')
	else:
		return render(request, 'reporter/remove.html')


@login_required()
def create(request):
	import updater

	if request.method == 'POST':
		form = ReportForm(request.POST)
		if form.is_valid():
			title = request.POST.get('title_text')
			content = request.POST.get('content_text')
			pub = timezone.now()
			report = Report(title_text=title, content_text=content, pub_date=pub)
			report.save()
			updater.start()
			return HttpResponseRedirect('/reports/' + str(report.id))
	else:
		return render(request, 'reporter/create.html')


@login_required()
def edit(request, report_id):
	report = get_object_or_404(Report, id=report_id)
	if request.method == 'POST':
		report.title_text = request.POST.get('title_text')
		report.content_text = request.POST.get('content_text')
		report.save()
		return HttpResponseRedirect('/reports/')
	else:
		return render(request, 'reporter/edit.html', {'report': report})


@login_required()
def download_excel(request, report_id):
	from openpyxl import Workbook
	from openpyxl.styles import Font, Alignment
	from openpyxl.utils import get_column_letter

	# TODO: Need to paste title and content of report

	file_name = 'Report ' + str(report_id) + '.xlsx'

	wb = Workbook()
	ws = wb.active
	ws.title = file_name

	ws['A1'] = 'ID'
	ws['A1'].font = Font(bold=True)
	ws['A1'].alignment = Alignment(horizontal='center')
	ws['B1'] = 'Name'
	ws['B1'].font = Font(bold=True)
	ws['B1'].alignment = Alignment(horizontal='center')
	ws['C1'] = 'State'
	ws['C1'].font = Font(bold=True)
	ws['C1'].alignment = Alignment(horizontal='center')
	ws['D1'] = 'RAM (kb)'
	ws['D1'].font = Font(bold=True)
	ws['D1'].alignment = Alignment(horizontal='center')
	ws['E1'] = 'Date'
	ws['E1'].font = Font(bold=True)
	ws['E1'].alignment = Alignment(horizontal='center')

	processes = Process.objects.all().filter(report=report_id)

	for i, process in enumerate(processes):
		ws.cell(row=i+2, column=1, value=processes[i].id)
		ws.cell(row=i+2, column=2, value=processes[i].name_text)
		ws.cell(row=i+2, column=3, value=processes[i].state_text)
		ws.cell(row=i+2, column=4, value=processes[i].ram_in_kb_int)
		ws.cell(row=i+2, column=5, value=processes[i].date)

	column_widths = []
	for i, cell in enumerate(ws[1]):
		column_widths += [len(cell.value)]

	for row in ws.rows:
		for i, cell in enumerate(row):
			length = len(str(cell.value)) + 2
			if length > column_widths[i]:

reportmaker/reporter/templates/reporter/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
	<meta charset="UTF-8">
	<link href="{% static 'reporter/style/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'reporter/images/favicon.ico' %}" rel="shortcut icon">
	{% block links %} {% endblock %}
	<title>{% block title %}{% endblock %}</title>
	{% block before_scripts %} {% endblock %}

</head>
<body class="bg-dark">
	{% block header %}
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<a class="navbar-brand" href="{% url 'reporter:index' %}">ReportMaker</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'reporter:index' %}">Home</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'reporter:reports' %}">Reports</a>
		      </li>
					<li class="nav-item">
		        <a class="nav-link" href="{% url 'reporter:create' %}">Add report</a>
		      </li>
		    </ul>

				{% if user.is_authenticated %}
					<ul class="navbar-nav mr-3 ml-auto">
			      <li class="nav-item dropdown">
			        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown"
			           aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
				      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
		          <a class="dropdown-item" href="{% url 'reporter:logout' %}">Logout</a>
	        </div>
			      </li>
					</ul>
					<form class="form-inline my-2 my-lg-0" action="{% url 'reporter:reports' %}" method="get">
			      <input class="form-control mr-sm-2" name="id_filter" type="search" placeholder="Find your report" aria-label="Search">
			      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
			    </form>
				{% else %}
					<ul class="navbar-nav mr-3 ml-auto">
			      <li class="nav-item">
							<a href="{% url 'reporter:login' %}" class="btn btn-outline-info my-2 my-sm-0">Login</a>
			      </li>
					</ul>
				{% endif %}
			</div>
		</nav>
	{% endblock %}
	<div class="content pt-4 mb-4">
		{% block content %} {% endblock %}
	</div>

	{% block footer %} {% endblock %}
</body>
<script src="{% static 'reporter/js/core/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'reporter/js/core/popper.min.js' %}"></script>
<script src="{% static 'reporter/js/core/bootstrap.min.js' %}"></script>
{% block after_scripts %} {% endblock %}
</html>

reportmaker/reporter/templates/reporter/create.html
{% extends "reporter/base.html" %}

{% load static %}

{% block title %}Report create{% endblock %}

{% block links %}
	<link href="{% static 'reporter/style/style.css' %}" rel="stylesheet">
{% endblock %}

{% block after_scripts %}
{% endblock %}

{% block content %}
	<div class="container d-flex justify-content-center">
		<div class="card form">
			<div class="card-body">
				<form class="p-3 d-flex flex-column" style="width: 500px" action="{% url 'reporter:create' %}" method="post">
					{% csrf_token %}
					<h5 class="card-title">Create new report</h5>
					<div class="input-group mb-2">
						<div class="input-group-prepend">
							<span class="input-group-text">Title</span>
						</div>
						<input class="form-control" type="text" name="title_text" maxlength="200" required >
					</div>
					<div class="input-group mb-2">
						<div class="input-group-prepend">
							<span class="input-group-text">Content</span>
						</div>
						<input class="form-control" type="text" name="content_text" maxlength="1000" required >
					</div>
					<div class="d-flex justify-content-between">
						<a class="btn btn-secondary text-white" href="{% url 'reporter:reports' %}">Reports</a>
						<input class="btn btn-primary" type="submit" value="Create" />
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

reportmaker/reporter/templates/reporter/index.html
{% extends "reporter/base.html" %}

{% load static %}

{% block title %}ReportMaker{% endblock %}

{% block content %}
<div class="jumbotron bg-dark text-light">
	<div class="row">
		<div class="col col-lg-7">
			<h1 class="display-4">Create your reports automatically</h1>
			<p class="lead">We help you create reports from your controllers and we will provide you with them in a pleasant visual form</p>
			<hr class="my-4 bg-light">
			<p>We make it better, more convenient and more beautiful</p>
			{% if user.is_authenticated %}
			<a class="btn btn-info btn-lg" href="{% url 'reporter:reports' %}" role="button">Go to reports</a>
			{% else %}
			<a class="btn btn-info btn-lg" href="{% url 'reporter:login' %}" role="button">Login</a>
			{% endif %}
		</div>
		<div class="col d-flex mt-5 mt-md-0 justify-content-end justify-content-md-center">
			<img width="300" src="{% static 'reporter/images/automation.svg' %}">
		</div>
	</div>
</div>
{% endblock %}

reportmaker/reporter/templates/reporter/report.html
{% extends "reporter/base.html" %}

{% load static %}

{% block links %}
	<link href="{% static 'reporter/style/style.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}List processes of report - {{report.id}}{% endblock %}

{% block content %}
	<div class="container-fluid">
		<div class="card">
			<div class="card-body">
				<h2 class="card-title">{{ report.id }} - {{ report.title_text }}</h2>
				<h5 class="card-subtitle my-2 text-muted">{{ report.content_text }}</h5>
				<span class="card-subtitle text-muted">Created: {{ report.pub_date }}</span>
			</div>
			<div class="card-body">
				<div class="row">
					<div class="col-12 col-lg-4">
						<div class="card filters">
							<div class="card-body">
								<h5 class="card-title">Filters</h5>
								<form action="" id="filter_form" method="get" class="text-right">
									<div class="input-group mb-2">
										<div class="input-group-prepend">
											<span class="input-group-text">id</span>
										</div>
										<input class="form-control" name="id_filter" form="filter_form" placeholder="Enter report id" value="{{ filters.id|default:'' }}">
									</div>
									<div class="input-group mb-2">
										<div class="input-group-prepend">
											<span class="input-group-text">Name</span>
										</div>
										<input class="form-control" name="name" placeholder="Enter phrase in name" value="{{ filters.name|default:'' }}">
										<select class="custom-select bg-light" name="name_match" style="max-width: 8em">
											<option value="exact" {% if filters.name_match == "exact" %}selected{% endif %}}}>Exact match</option>
											<option value="starts" {% if filters.name_match == "starts" %}selected{% endif %}>Starts with</option>
											<option value="contains" {% if filters.name_match == "contains" %}selected{% endif %}>Contains</option>
											<option value="ends" {% if filters.name_match == "ends" %}selected{% endif %}>Ends with</option>
										</select>
									</div>
									<div class="input-group mb-2">
										<div class="input-group-prepend">
											<span class="input-group-text">State</span>
										</div>
										<input class="form-control" name="state"  placeholder="Enter phrase in state" value="{{ filters.state|default:'' }}">
										<select class="custom-select bg-light" name="state_match" style="max-width: 8em">
											<option value="exact" {% if filters.state_match == "exact" %}selected{% endif %}>Exact match</option>
											<option value="starts" {% if filters.state_match == "starts" %}selected{% endif %}>Starts with</option>
											<option value="contains" {% if filters.state_match == "contains" %}selected{% endif %}>Contains</option>
											<option value="ends" {% if filters.state_match == "ends" %}selected{% endif %}>Ends with</option>
										</select>
									</div>
									<div class="input-group mb-2">
										<div class="input-group-prepend">
											<span class="input-group-text">RAM</span>
										</div>
										<input class="form-control" name="ram"  placeholder="Enter the amount of RAM" value="{{ filters.ram|default:'' }}">
										<select class="custom-select bg-light" name="ram_match" style="max-width: 8em">
											<option value="equal" {% if filters.ram_match == "equal" %}selected{% endif %}>Equal</option>
											<option value="greater" {% if filters.ram_match == "greater" %}selected{% endif %}>Greater</option>
											<option value="e_greater" {% if filters.ram_match == "e_greater" %}selected{% endif %}>Greater or equal</option>
											<option value="less" {% if filters.ram_match == "less" %}selected{% endif %}>Less</option>
											<option value="e_less" {% if filters.ram_match == "e_less" %}selected{% endif %}>Less or equal</option>
										</select>
									</div>
									<div class="input-group mb-2">
										<div class="input-group-prepend">
											<span class="input-group-text">Date</span>
										</div>
										<input class="form-control" name="date" type="date" placeholder="Enter date" value="{{ filters.date|default:'' }}">
										<select class="custom-select bg-light" name="date_match" style="max-width: 8em">
											<option value="equal" {% if filters.date_match == "equal" %}selected{% endif %}>Equal</option>
											<option value="greater" {% if filters.date_match == "greater" %}selected{% endif %}>Greater</option>
											<option value="e_greater" {% if filters.date_match == "e_greater" %}selected{% endif %}>Greater or equal</option>
											<option value="less" {% if filters.date_match == "less" %}selected{% endif %}>Less</option>
											<option value="e_less" {% if filters.date_match == "e_less" %}selected{% endif %}>Less or equal</option>
										</select>
									</div>
									<a href="{% url 'reporter:report' report.id %}" class="btn btn-outline-danger">Clear</a>
									<button class="btn btn-info" type="submit" style="width: 7em;">Filter</button>
								</form>
							</div>
						</div>
						<div class="card mt-3">
							<div class="card-body">
								<h5 class="card-title">Download this report</h5>
								<div class="d-flex">
									<a class="btn btn-outline-info w-100 mr-1" href="{% url 'reporter:download_excel' report.id %}">Excel</a>
									<a class="btn btn-outline-info w-100 ml-1" href="{% url 'reporter:download_word' report.id %}">Word</a>
								</div>
							</div>
						</div>
					</div>
					<div class="col-12 col-lg-8 mt-3 mt-lg-0">
						<div class="card filters">
							<div class="card-body" style="overflow-x: auto;">
								<table class="table table-light table-hover">
									<thead class="thead-light">
										<tr>
											<th>ID</th>
											<th>Name</th>
											<th>State</th>
											<th>RAM (kb)</th>
											<th>Date</th>
										</tr>
									</thead>
									{% for process in process_list %}
										<tr>
											<td>{{ process.id }}</td>
											<td>{{ process.name_text }}</td>
											<td>{{ process.state_text }}</td>
											<td>{{ process.ram_in_kb_int }}</td>
											<td>{{ process.date }}</td>
										</tr>
									{% empty %}
										<tr>
											<td class="text-center" colspan="5">Nothing to show</td>
										</tr>
									{% endfor %}
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

reportmaker/reporter/templates/reporter/report_list.html
{% extends "reporter/base.html" %}

{% load static %}

{% block title %}List of reports{% endblock %}

{% block links %}
	<link href="{% static 'reporter/style/style.css' %}" rel="stylesheet">
{% endblock %}

{% block after_scripts %}
{% endblock %}

{% block content %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-12 col-lg-4">
				<div class="card filters">
					<div class="card-body">
						<h5 class="card-title">Filters</h5>
						<form action="" id="filter_form" method="get" class="text-right">
							<div class="input-group mb-2">
								<div class="input-group-prepend">
									<span class="input-group-text">id</span>
								</div>
								<input class="form-control" name="id" placeholder="Enter report id" value="{{ filters.id|default:'' }}">
							</div>
							<div class="input-group mb-2">
								<div class="input-group-prepend">
									<span class="input-group-text">Title</span>
								</div>
								<input class="form-control" name="title" placeholder="Enter phrase in title" value="{{ filters.title|default:'' }}">
								<select class="custom-select bg-light" name="title_match" style="max-width: 8em">
									<option value="exact" {% if filters.title_match == "exact" %}selected{% endif %}>Exact match</option>
									<option value="starts" {% if filters.title_match == "starts" %}selected{% endif %}>Starts with</option>
									<option value="contains" {% if filters.title_match == "contains" %}selected{% endif %}>Contains</option>
									<option value="ends" {% if filters.title_match == "ends" %}selected{% endif %}>Ends with</option>
								</select>
							</div>
							<div class="input-group mb-2">
								<div class="input-group-prepend">
									<span class="input-group-text">Content</span>
								</div>
								<input class="form-control" name="content"  placeholder="Enter phrase in content" value="{{ filters.content|default:'' }}">
								<select class="custom-select bg-light" name="content_match" style="max-width: 8em">
									<option value="exact" {% if filters.content_match == "exact" %}selected{% endif %}>Exact match</option>
									<option value="starts" {% if filters.content_match == "starts" %}selected{% endif %}>Starts with</option>
									<option value="contains" {% if filters.content_match == "contains" %}selected{% endif %}>Contains</option>
									<option value="ends" {% if filters.content_match == "ends" %}selected{% endif %}>Ends with</option>
								</select>
							</div>
							<div class="input-group mb-2">
								<div class="input-group-prepend">
									<span class="input-group-text">Date</span>
								</div>
								<input class="form-control" name="date" type="date" placeholder="Filter by date" value="{{ filters.date|default:'' }}">
								<select class="custom-select bg-light" name="date_match" style="max-width: 8em">
											<option value="equal" {% if filters.date_match == "equal" %}selected{% endif %}>Equal</option>
											<option value="greater" {% if filters.date_match == "greater" %}selected{% endif %}>Greater</option>
											<option value="e_greater" {% if filters.date_match == "e_greater" %}selected{% endif %}>Greater or equal</option>
											<option value="less" {% if filters.date_match == "less" %}selected{% endif %}>Less</option>
											<option value="e_less" {% if filters.date_match == "e_less" %}selected{% endif %}>Less or equal</option>
										</select>
							</div>
							<a href="{% url 'reporter:reports' %}" class="btn btn-outline-danger">Clear</a>
							<button class="btn btn-info" type="submit" style="width: 7em;">Filter</button>
						</form>
					</div>
				</div>
			</div>
			<div class="col-12 col-lg-8 mt-3 mt-lg-0">
				<div class="card">
					<div class="card-body" style="overflow-x: auto;">
						<table class="table table-light table-hover without-last-tr">
							<thead class="thead-light">
								<tr>
									<th>ID</th>
									<th>Title</th>
									<th>Content</th>
									<th>Date&nbsp;published</th>
									<th></th>
								</tr>
							</thead>
							{% if report_list %}
								{% for report in report_list %}
									<tr>
										<td>{{ report.id }}</td>
										<td><a href="{% url 'reporter:report' report.id %}">{{ report.title_text }}</a></td>
										<td>{{ report.content_text }}</td>
										<td>{{ report.pub_date }}</td>
										<td>
											<div class="d-flex justify-content-end">
												<a class="btn btn-outline-info mr-1 table-btn" href="{% url 'reporter:report_edit' report.id %}">Edit</a>
												<a class="btn btn-outline-danger table-btn" href="{% url 'reporter:report_remove' report.id %}">Remove</a>
											</div></td>
									</tr>
								{% endfor %}
							{% else %}
								<tr>
									<td class="text-center" colspan="5">Nothing to show</td>
								</tr>
							{% endif %}
						</table>
						<div class="d-flex justify-content-end mr-2">
							<a class="btn btn-outline-primary table-btn mr-1" href="{% url 'reporter:create' %}">Add report</a>
						</div>
					</div>
				</div>
			</div>
		</div>


	</div>

{% endblock %}